### PR TITLE
invert config should be bools

### LINKED ISSUE #3: Invert config should use boolean values
```
{ "input": 7, "type": "button", "invert": true }
```

### PR DESCRIPTION
**Pull request by sumnerboy12**
Need to ~~update the README~~ and test

### CODE REVIEW

**Comment by sumnerboy12** [comment]
@moinmoin-sh can you have a look at this and check it looks ok - as I can't test it currently. I have already updated the docs on https://oxrs.io/docs/firmware/state-monitor-esp32.html.

**Comment by sumnerboy12** [comment]
Did some testing in another piece of firmware using `json["key"].as<bool>()` and pretty happy this is ok.

**Comment by moinmoin-sh** [comment]
doesn't seem to work for me. 
`mosquitto_pub -h debian9 -t conf/osm-58391f -m '{"index":8, "type":"button", "invert":"false"}'`
`mosquitto_pub -h debian9 -t conf/osm-58391f -m '{"index":8, "type":"button", "invert":"true"}'`
both of them are setting `invert `to `true`. Can't reset `invert `to `false`
(using your newest branch)

**Comment by sumnerboy12** [comment]
Don't put quotes around the book values

**Comment by moinmoin-sh** [comment]
that helps ;-)

**Pull request merged**
